import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/components/shared";
import { Inter } from "next/font/google";
import { MAXWIDTH } from "@/lib/const-css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header className={`${MAXWIDTH} mx-auto`} />
        {children}
        <Footer className="mx-auto"/>
      </body>
    </html>
  );
}
